server:
  port: 8090
spring:          #表示该配置直接为Spring容器负责处理
　　datasource:
  　　type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个
  　　driver-class-name: com.mysql.jdbc.Driver       #配置MySQL的驱动程序类
  　　url: jdbc:mysql://localhost:3306/my_project?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  　　username: root
  　　password: 123456
  　　filters: stat,wall,log4j     #druid监控配置
  　　druid:
       initial-size: 5
       min-idle: 5
       max-active: 20
       # 配置获取连接等待超时的时间
       max-wait: 60000
         # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
       time-between-eviction-runs-millis: 60000
         # 配置一个连接在池中最小生存的时间，单位是毫秒
       min-evictable-idle-time-millis: 300000
         # Oracle请使用select 1 from dual
       validation-query: SELECT 'x'
       test-while-idle: true
       test-on-borrow: false
       test-on-return: false
         # 打开PSCache，并且指定每个连接上PSCache的大小
       pool-prepared-statements: true
       max-pool-prepared-statement-per-connection-size: 20
         # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
       filters: stat,wall,slf4j
         # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
       connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
         # 合并多个DruidDataSource的监控数据
       use-global-data-source-stat: true

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
